title: "Antony Mbugua"
description: "Portfolio & Writeups — Cybersecurity, Secure Development"
baseurl: ""     # leave blank for user.github.io
url: "https://antony-mbugua.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Antony Mbugua Githinji"
  avatar: "/assets/images/avatar.png"
  bio: "Cybersecurity & Full-Stack Developer — secure systems, writeups, and automation."

collections:
  writeups:
    output: true
  projects:
    output: true

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Writeups"
    url: /writeups/
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
